DECLARE @DATASAIDA VARCHAR(10)
DECLARE @CODMATRICULA VARCHAR(50)

DECLARE CR_ATUALIZA_DATAS CURSOR FOR
	SELECT 
	MAT_CODMATRICULA,
	CONVERT(DATE,DATASAIDAPREVISTA) DATASAIDAPREVISTA
	FROM
	Planilha1$

OPEN CR_ATUALIZA_DATAS

FETCH NEXT FROM CR_ATUALIZA_DATAS INTO @CODMATRICULA,@DATASAIDA
WHILE @@FETCH_STATUS = 0
BEGIN
	UPDATE Planilha1$
	SET DTSAIDA = @DATASAIDA
	WHERE MAT_CODMATRICULA = @CODMATRICULA

	FETCH NEXT FROM CR_ATUALIZA_DATAS INTO @CODMATRICULA,@DATASAIDA
END
CLOSE CR_ATUALIZA_DATAS
DEALLOCATE CR_ATUALIZA_DATAS
