DECLARE @DATASAIDA VARCHAR(10)
DECLARE @CODMATRICULA VARCHAR(50)

DECLARE CR_ATUALIZA_DATAS CURSOR FOR
	SELECT 
	CODMATRICULA,
	DT_SAIDA_PREVISTA
	FROM
	ZVSI

OPEN CR_ATUALIZA_DATAS

FETCH NEXT FROM CR_ATUALIZA_DATAS INTO @CODMATRICULA,@DATASAIDA
WHILE @@FETCH_STATUS = 0
BEGIN
	UPDATE ZVSI
	SET DT_SAIDA = @DATASAIDA
	WHERE CODMATRICULA = @CODMATRICULA
	FETCH NEXT FROM CR_ATUALIZA_DATAS INTO @CODMATRICULA,@DATASAIDA
END
CLOSE CR_ATUALIZA_DATAS
DEALLOCATE CR_ATUALIZA_DATAS
