
DECLARE @DE DATETIME
DECLARE @ATE DATETIME

SET @DE = '2019-01-04'
SET @ATE = '2019-30-04'

SELECT

SPT.CODPROF,
--STD.CODTURMA,
SP.CHAPA,
--SD.NOME,
COUNT(SPL.DATA) AS AULAS

FROM SPLANOAULA SPL (NOLOCK)

INNER JOIN SHORARIOTURMA SHT (NOLOCK) ON
	SHT.CODCOLIGADA = SPL.CODCOLIGADA AND
	SHT.CODFILIAL = SPL.CODFILIAL AND
	SHT.IDHORARIOTURMA = SPL.IDHORARIOTURMA

INNER JOIN SHORARIOPROFESSOR SHP (NOLOCK) ON
	SHP.CODCOLIGADA = SHT.CODCOLIGADA AND
	SHP.IDHORARIOTURMA = SHT.IDHORARIOTURMA

INNER JOIN SPROFESSORTURMA SPT (NOLOCK) ON
	SHP.CODCOLIGADA = SPT.CODCOLIGADA AND
	SHP.IDPROFESSORTURMA = SPT.IDPROFESSORTURMA

INNER JOIN SPROFESSOR SP (NOLOCK) ON
	SP.CODCOLIGADA = SPT.CODCOLIGADA AND
	SP.CODPROF =  SPT.CODPROF

INNER JOIN STURMADISC STD (NOLOCK) ON
	STD.CODCOLIGADA = SPT.CODCOLIGADA AND
	STD.IDTURMADISC = SPT.IDTURMADISC

INNER JOIN
STURMADISCCOMPL STDC (NOLOCK) ON
STDC.CODCOLIGADA = STD.CODCOLIGADA AND
STDC.IDTURMADISC = STD.IDTURMADISC

INNER JOIN SDISCIPLINA SD (NOLOCK) ON
	STD.CODDISC = SD.CODDISC AND
	STD.CODCOLIGADA = SD.CODCOLIGADA

WHERE 
	SPL.CODCOLIGADA = 3 AND
	SPL.CODFILIAL = 4 AND
	STDC.GAET = '1' AND
	--SPT.CODPROF = 19155 AND
	SPL.DATA BETWEEN @DE AND @ATE
	--SP.CHAPA = '02019'

GROUP BY

SPT.CODPROF,
SP.CHAPA
--STD.CODTURMA,
--SD.NOME