DECLARE @DE DATE
DECLARE @ATE DATE
SET @DE = '2017-12-01'
SET @ATE = '2017-12-31'

SELECT * FROM VW_CURSOS WHERE CODCURSO IN (SELECT DISTINCT CD_CURSO FROM ZVSI WHERE CONVERT(DATE,DT_SAIDA) BETWEEN @DE AND @ATE)
SELECT * FROM ZVSI  WHERE CONVERT(DATE,DT_SAIDA) BETWEEN @DE AND @ATE

SELECT
CH.TIPOREG,
CH.OPERACAO,
CH.CODMATRICULA,
CONVERT(VARCHAR(10),@DE,103) CHMESANO,
CH.CH_FESCOLAR,
CH.CH_FESTAGIO,
CH.CH_PRAPROFISSIONAL

FROM 
VW_CH_SI CH
WHERE CODMATRICULA IN (SELECT DISTINCT CODMATRICULA FROM ZVSI WHERE CONVERT(DATE,DT_SAIDA) BETWEEN @DE AND @ATE)