ALTER FUNCTION FN_HORAS_TRABALHADAS(@SEGUNDOS INT)
RETURNS VARCHAR(8)
BEGIN
DECLARE @RESULTADO VARCHAR(8)
	SET @RESULTADO = FORMAT(SUM(@SEGUNDOS)/3600,'00')+':';
	SET @RESULTADO = @RESULTADO + FORMAT((SUM(@SEGUNDOS)%3600)/60,'00')+':';
	SET @RESULTADO = @RESULTADO + FORMAT((SUM(@SEGUNDOS)%3600)%60,'00');
	RETURN @RESULTADO
END

SELECT DBO.FN_HORAS_TRABALHADAS(15000) AS HORASTRABALHADAS;